{{- if eq .Values.database.type "internal" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "safeline.database.host" . }}
  labels:
{{ include "safeline.labels" . | indent 4 }}
spec:
  ports:
    - port: 5432
  selector:
{{ include "safeline.matchLabels" . | indent 4 }}
    component: database
{{- end -}}