nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
imagePullPolicy: IfNotPresent

global:
  image:
    registry: swr.cn-east-3.myhuaweicloud.com/chaitin-safeline
    tag: ""

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    database:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteOnce
      size: 1Gi
      annotations: {}

    sock:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    logs:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    nginx:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    mgt:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    detector:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    mario:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    tengine:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    luigi:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    bridge:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    chaos:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

database:
  type: internal
  internal:
    serviceAccountName: ""
    automountServiceAccountToken: false
    image:
      registry: ''
      repository: postgres
      tag: 15.2
    password: changeit
    shmSizeLimit: 512Mi
    resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
    livenessProbe:
      timeoutSeconds: 1
    readinessProbe:
      timeoutSeconds: 1
    nodeSelector: {}
    tolerations: []
    affinity: {}
    priorityClassName:
    initContainer:
      migrator: {}
      # resources:
      #  requests:
      #    memory: 128Mi
      #    cpu: 100m
      permissions: {}
      # resources:
      #  requests:
      #    memory: 128Mi
      #    cpu: 100m
  external:
    host: ""
    port: ""
    username: ""
    password: ""
    coreDatabase: "safeline-ce"
    dbname: "safeline-ce"
    existingSecret: ""
    sslmode: "disable"
  maxIdleConns: 100
  maxOpenConns: 900
  podAnnotations: {}

mgt:
  image:
    registry: ''
    repository: safeline-mgt
    tag: ""
  service:
    type: NodePort
    web:
      nodePort: 31443
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

fvm:
  image:
    registry: ''
    repository: safeline-fvm
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 


detector:
  image:
    registry: 'uhub.service.ucloud.cn/silkdo/chaitin'
    repository: safeline-detector
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

mario:
  image:
    registry: ''
    repository: safeline-mario
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

tengine:
  image:
    registry: 'uhub.service.ucloud.cn/silkdo/chaitin'
    repository: safeline-tengine
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

luigi:
  image:
    registry: ''
    repository: safeline-luigi
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

bridge:
  image:
    registry: ''
    repository: safeline-bridge
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

chaos:
  image:
    registry: ''
    repository: safeline-chaos
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 
