apiVersion: v1
kind: Service
metadata:
  name: "{{ template "safeline.chaos" . }}"
  labels:
{{ include "safeline.labels" . | indent 4 }}
spec:
{{- if or (eq .Values.chaos.service.type "NodePort") (eq .Values.chaos.service.type "LoadBalancer") }}
  type: NodePort
{{- end }}
  ports:
    - name: chaos
      protocol: TCP
      port: {{ template "safeline.chaos.port" . }}
    - name: auth
      protocol: TCP
      port: {{ template "safeline.chaos.auth.port" . }}
    - name: challenge
      protocol: TCP
      port: {{ template "safeline.chaos.challenge.port" . }}
  selector:
{{ include "safeline.matchLabels" . | indent 4 }}
    component: chaos
