apiVersion: v1
kind: Service
metadata:
  name: {{ template "safeline.detector" . }}
  labels:
{{ include "safeline.labels" . | indent 4 }}
spec:
  ports:
    - name: snserver
      port: {{ template "safeline.detector.port" . }}
  selector:
{{ include "safeline.matchLabels" . | indent 4 }}
    component: detector
