apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "safeline.bridge" . }}
  labels:
{{ include "safeline.labels" . | indent 4 }}
    component: bridge
spec:
  replicas: {{ .Values.bridge.replicas }}
  revisionHistoryLimit: {{ .Values.bridge.revisionHistoryLimit }}
  strategy:
{{- if .Values.strategy }}
{{ toYaml .Values.strategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
{{ include "safeline.matchLabels" . | indent 6 }}
      component: bridge
  template:
    metadata:
      labels:
{{ include "safeline.matchLabels" . | indent 8 }}
        component: bridge
      annotations:
{{- if .Values.bridge.podAnnotations }}
{{ toYaml .Values.bridge.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.bridge.serviceAccountName }}
      serviceAccountName: {{ .Values.bridge.serviceAccountName }}
{{- end -}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.bridge.automountServiceAccountToken | default false }}
      terminationGracePeriodSeconds: 120
      initContainers:
      - name: delete-lost-found-dir
        image: {{ default .Values.global.image.registry .Values.bridge.image.registry }}/{{ .Values.bridge.image.repository }}:{{ default .Chart.AppVersion .Values.bridge.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - sh
          - -c
          - |-
            rm -rf /app/run/lost+found
        volumeMounts:
          - mountPath: /app/run
            name: bridge
      containers:
      - name: bridge
        image: {{ default .Values.global.image.registry .Values.bridge.image.registry }}/{{ .Values.bridge.image.repository }}:{{ default .Chart.AppVersion .Values.bridge.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - /app/bridge
          - serve
          - -n
          - unix
          - -a
          - /app/run/safeline.sock
        volumeMounts:
          - mountPath: /app/run
            name: bridge
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
{{- if .Values.bridge.resources }}
        resources:
{{ toYaml .Values.bridge.resources | indent 10 }}
{{- end }}
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime

        {{- if .Values.persistence.enabled }}
        - name: bridge
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.persistentVolumeClaim.bridge.existingClaim | default (include "safeline.bridge" .) }}
        {{- else -}}
        - name: bridge
          emptyDir: {}
        {{- end -}}

    {{- with .Values.bridge.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.bridge.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.bridge.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.bridge.priorityClassName }}
      priorityClassName: {{ .Values.bridge.priorityClassName }}
    {{- end }}
