{{- $bridge := .Values.persistence.persistentVolumeClaim.bridge -}}
{{- if and .Values.persistence.enabled (not $bridge.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "safeline.bridge" . }}
  annotations:
  {{- range $key, $value := $bridge.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "safeline.labels" . | indent 4 }}
    component: bridge
spec:
  accessModes: 
    - {{ $bridge.accessMode }}
  resources:
    requests:
      storage: {{ $bridge.size }}
  {{- if $bridge.storageClass }}
    {{- if eq "-" $bridge.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $bridge.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
