{{- $nginx := .Values.persistence.persistentVolumeClaim.nginx -}}
{{- if and .Values.persistence.enabled (not $nginx.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "safeline.nginx" . }}
  annotations:
  {{- range $key, $value := $nginx.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "safeline.labels" . | indent 4 }}
    component: nginx
spec:
  accessModes: 
    - {{ $nginx.accessMode }}
  resources:
    requests:
      storage: {{ $nginx.size }}
  {{- if $nginx.storageClass }}
    {{- if eq "-" $nginx.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $nginx.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
