{{- $run := .Values.persistence.persistentVolumeClaim.run -}}
{{- if and .Values.persistence.enabled (not $run.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "safeline.run" . }}
  annotations:
  {{- range $key, $value := $run.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "safeline.labels" . | indent 4 }}
    component: run
spec:
  accessModes: 
    - {{ $run.accessMode }}
  resources:
    requests:
      storage: {{ $run.size }}
  {{- if .Values.global.persistence.storageClass }}
  storageClassName: {{ .Values.global.persistence.storageClass }}
  {{- else if $run.storageClass }}
    {{- if eq "-" $run.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $run.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
